<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hobot_locateanything</name>
  <version>0.1.1</version>
  <description>LocateAnything-3B HBM inference for D-Robotics RDK S600 and TROS.</description>
  <maintainer email="3071744684@qq.com">Kangjie Xu</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ament_index_cpp</depend>
  <depend>ai_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>hbm_img_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>yaml-cpp</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>hobot_codec</exec_depend>
  <exec_depend>hobot_image_publisher</exec_depend>
  <exec_depend>hobot_shm</exec_depend>
  <exec_depend>hobot_usb_cam</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>mipi_cam</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
